### PR TITLE
RATPAC comparison (relies on PR #6)

### PR DESCRIPTION
**Pull request by mnieslony**
The physics list used in RATPAC has been inserted for comparison studies between the two simulation packages (WCSim/RATPAC) in the scope of ANNIE. The list is defined in `PhysicsListRAT` and relies on other classes (`DummyProcess`, `GLG4OpAttenuation`) which were also copied over from the ANNIE RATPAC framework.

The RATPAC physics list can be selected in `macros/jobOptions.mac` by typing
```
/WCSim/physics/list RATPAC
```

Main differences lie in the use of the `Shielding` list for RATPAC instead of `FTFPBERT_HP` in the case of WCSim and some additional minor differences. 

Some material property values from RATPAC were added in the `ConstructMaterials` class and can be used by uncommenting lines of code in the class for material construction. In addition, the number of Cherenkov photons can now be saved on an event-by-event basis. If desired, also histograms with the wavelength distribution of produced Cherenkov photons can be saved by uncommenting some lines in `WCSimEventAction.cc`.

From simple comparison tests with the same event topology, RATPAC seems to produce slightly more Cherenkov photons than WCSim for some reason. However, the cause for this difference could not be tracked down (using the RATPAC physics list in WCSim did not resolve the discrepancy). This PR should make it easier to continue similar studies, if needed in the future.

### CODE REVIEW

**Comment by marc1uk** [comment]
This is kinda a lot....it could be useful for comparisons, but my concerns are code bloat and performance impacts.

Does [this](https://github.com/ANNIEsoft/WCSim/pull/9/files/cde18b29e44ac616b01391a070172958ca01f0f8..68159d4cb7c0213a883383f85cc356154de1ad94#diff-3ce4676cd88fa1c8bbd30e9c75a2d7ceb949b12b5d03d4e06d76c92e0a0b4ef7R122) impact performance, for example? (if so, maybe only set it when using the RAT physics list?)
Does [this](https://github.com/ANNIEsoft/WCSim/pull/9/files/cde18b29e44ac616b01391a070172958ca01f0f8..68159d4cb7c0213a883383f85cc356154de1ad94#diff-fd75c9ad32a34d3d8dbc46b8866699d85808e98cc84b770eaba9491870021e6aR71)? Might be nice for some pretty plots of photon production points, but those seem like a very niche case. If they're not being written out, it'd be better not to make them.
Does [this](https://github.com/ANNIEsoft/WCSim/pull/9/files/cde18b29e44ac616b01391a070172958ca01f0f8..68159d4cb7c0213a883383f85cc356154de1ad94#diff-e417b44b5b201c26978a86da24722a6d4cee6f8896840d24409d6bbf946f6b7aR1754)? (or is it needed...?)

Is [here](https://github.com/ANNIEsoft/WCSim/pull/9/files/cde18b29e44ac616b01391a070172958ca01f0f8..68159d4cb7c0213a883383f85cc356154de1ad94#diff-12b17e76d0ebeeb741e1a7b55be1c799ca01b316991ddcb64a43294250f2e557R149) the right place for this? I feel like it would be better in the WCSimEventAction, since it's EventInformation. It's got nothing to do with primary generation...

[Just testing...?](https://github.com/ANNIEsoft/WCSim/pull/9/files/cde18b29e44ac616b01391a070172958ca01f0f8..68159d4cb7c0213a883383f85cc356154de1ad94#diff-387a6520d5c88d9ac37a735b615d16ca9acac9280bad2fbcd57f4c1eca620d07R172)

I'm sure you're aware, but bear in mind that changing the output file classes - the WCSimRootEventAction - will impact the resulting root dictionary and libraries needed to read WCSim outputs. That means making sure the updated definitions are in the ToolAnalysis repository, and getting people to use the right library for the right fileset. Maybe it's time to start following proper root schema evolution and update the classdef version number...

>Some material property values from RATPAC were added in the ConstructMaterials class and can be used by uncommenting lines of code in the class for material construction. 

It might be better to make this configurable by a boolean or something. We have so much commented out old code already, there'd be no way to tell this is supposed to be a feature and not just more cruft. :grimacing: 

Is this related to all the random extra [commented out elements](https://github.com/ANNIEsoft/WCSim/pull/9/files/cde18b29e44ac616b01391a070172958ca01f0f8..68159d4cb7c0213a883383f85cc356154de1ad94#diff-d6346ffd4aaf49203bb9e76adb4664bf33595f8fafa94e36e6fda89a52f7e799R755)? 

Is the DummyProcess actually needed? Maybe i just didn't spot it, but i couldn't spot anything that used it....

Is it too much to ask to not add [`using namespace std`](https://github.com/ANNIEsoft/WCSim/pull/9/files/cde18b29e44ac616b01391a070172958ca01f0f8..68159d4cb7c0213a883383f85cc356154de1ad94#diff-e29899c7d6c044d45a2c55de3f8c46c6ecea13d0990c84e7d774c602a709bee3R25) - importing a namespace impacts the entire c++ project, not just that file. I assume it doesn't, but introducing it here could result in variable name conflicts in an entirely different file, for example (e.g. someone has a variable called 'max', that now turns into a function...). Personally I feel it's better to use std:: prefixes where necessary. 

Maybe i'm just tired, sorry for all the pedantic comments in this one....

**Comment by mnieslony** [comment]
Hey Marcus, thanks a lot for looking over it!
Let me get back to your questions:

> Does [this](https://github.com/ANNIEsoft/WCSim/pull/9/files/cde18b29e44ac616b01391a070172958ca01f0f8..68159d4cb7c0213a883383f85cc356154de1ad94#diff-3ce4676cd88fa1c8bbd30e9c75a2d7ceb949b12b5d03d4e06d76c92e0a0b4ef7R122) impact performance, for example? (if so, maybe only set it when using the RAT physics list?) 

I didn't notice any difference, but the variable is now only set to a value of 1 in case the `RATPAC` physics list is used.

>Does [this](https://github.com/ANNIEsoft/WCSim/pull/9/files/cde18b29e44ac616b01391a070172958ca01f0f8..68159d4cb7c0213a883383f85cc356154de1ad94#diff-fd75c9ad32a34d3d8dbc46b8866699d85808e98cc84b770eaba9491870021e6aR71)? Might be nice for some pretty plots of photon production points, but those seem like a very niche case. If they're not being written out, it'd be better not to make them. 

I just used the photon wavelength histogram plots for some more detailed comparison studies. But I agree that they normally shouldn't be filled for every event, so they are now commented out.

>Does [this](https://github.com/ANNIEsoft/WCSim/pull/9/files/cde18b29e44ac616b01391a070172958ca01f0f8..68159d4cb7c0213a883383f85cc356154de1ad94#diff-e417b44b5b201c26978a86da24722a6d4cee6f8896840d24409d6bbf946f6b7aR1754)? (or is it needed...?)

Not needed, so I removed the line.

> Is [here](https://github.com/ANNIEsoft/WCSim/pull/9/files/cde18b29e44ac616b01391a070172958ca01f0f8..68159d4cb7c0213a883383f85cc356154de1ad94#diff-12b17e76d0ebeeb741e1a7b55be1c799ca01b316991ddcb64a43294250f2e557R149) the right place for this? I feel like it would be better in the WCSimEventAction, since it's EventInformation. It's got nothing to do with primary generation...

So for me it seemed to be natural to put it in the `PrimaryGeneratorAction`, since the event is initialized there, and the event information should be set during initialization. It's possible that another place might be more natural, but I don't think it would influence performance in any way.

> [Just testing...?](https://github.com/ANNIEsoft/WCSim/pull/9/files/cde18b29e44ac616b01391a070172958ca01f0f8..68159d4cb7c0213a883383f85cc356154de1ad94#diff-387a6520d5c88d9ac37a735b615d16ca9acac9280bad2fbcd57f4c1eca620d07R172)

Yeah, that shouldn't be in the final version. Commented the lines out.

> I'm sure you're aware, but bear in mind that changing the output file classes - the WCSimRootEventAction - will impact the resulting root dictionary and libraries needed to read WCSim outputs. That means making sure the updated definitions are in the ToolAnalysis repository, and getting people to use the right library for the right fileset. Maybe it's time to start following proper root schema evolution and update the classdef version number...
> 
> > Some material property values from RATPAC were added in the ConstructMaterials class and can be used by uncommenting lines of code in the class for material construction.
> 
> It might be better to make this configurable by a boolean or something. We have so much commented out old code already, there'd be no way to tell this is supposed to be a feature and not just more cruft. 😬
> Is this related to all the random extra [commented out elements](https://github.com/ANNIEsoft/WCSim/pull/9/files/cde18b29e44ac616b01391a070172958ca01f0f8..68159d4cb7c0213a883383f85cc356154de1ad94#diff-d6346ffd4aaf49203bb9e76adb4664bf33595f8fafa94e36e6fda89a52f7e799R755)?

Good point. There are now two variables that configure whether the RATPAC-specific material properties are used and whether photons should be simulated down to 60nm as in RATPAC (in WCSim, the default is 200nm). I put those variables in the `TuningMessenger`, since the `DetectorMessenger` seems to be called only after the materials have already been constructed.

> Is the DummyProcess actually needed? Maybe i just didn't spot it, but i couldn't spot anything that used it....

The `DummyProcess` is used in `GLG4OpAttenuation.cc` for setting up attenuation and scattering processes in the scope of the RATPAC physics list. Not sure what it's doing exactly, but it seems to be needed.

> Is it too much to ask to not add [`using namespace std`](https://github.com/ANNIEsoft/WCSim/pull/9/files/cde18b29e44ac616b01391a070172958ca01f0f8..68159d4cb7c0213a883383f85cc356154de1ad94#diff-e29899c7d6c044d45a2c55de3f8c46c6ecea13d0990c84e7d774c602a709bee3R25) - importing a namespace impacts the entire c++ project, not just that file. I assume it doesn't, but introducing it here could result in variable name conflicts in an entirely different file, for example (e.g. someone has a variable called 'max', that now turns into a function...). Personally I feel it's better to use std:: prefixes where necessary.

No problem, I removed `using namespace` from `GLG4OpAttenuation`. When looking through all files, I noticed that there is another `using namespace` call in `src/SBsimMRDDB.cc` - maybe you want to have a look at that?

> Maybe i'm just tired, sorry for all the pedantic comments in this one....

I think they were all pretty valid concerns, so no problem and thanks for looking through the code changes!

**Comment by marc1uk** [comment]
Thanks for making all these changes.

Mostly for my own benefit, but also for any other developers, may I ask for some explanation as to what's going on around [here](https://github.com/ANNIEsoft/WCSim/pull/9/files/68159d4cb7c0213a883383f85cc356154de1ad94..6da244bc4fe5f7de54fb9aa6cd727fc41a765523#diff-3ce4676cd88fa1c8bbd30e9c75a2d7ceb949b12b5d03d4e06d76c92e0a0b4ef7R74)?
Evidently registering neutron capture models and such, but I get a bit lost in all the G4 calls. What cross-section ends up being used? Is it the HP one? Does this still ensure we're activating the material-specific thermal neutron modelling? Why is there a 20MeV energy limit applied to the radiative capture process? 

Perhaps this is something that another developer can do as a proper investigation, as I realise it's a lot of work, but it would be interesting to see what impact all these changes are having, and ensure neutron capture is indeed being handled how we think. All this code wasn't here until this last round of commits, so presumably it's all to support Geant4 pre-10.2 - are there validation plots with G4.10.2 from before and after this change, to ensure it's functioning as expected?

Can you remind me why [the R7081's have their glass handled differently](https://github.com/ANNIEsoft/WCSim/pull/9/files/68159d4cb7c0213a883383f85cc356154de1ad94..6da244bc4fe5f7de54fb9aa6cd727fc41a765523#diff-d6346ffd4aaf49203bb9e76adb4664bf33595f8fafa94e36e6fda89a52f7e799R1192)? Different reflectivity tuning iirc? What impact does that have, exactly? Is there justification for it? Maybe you could put a comment in explaining it.... :grin:

**Comment by mnieslony** [comment]
So most of these changes were in other PRs and just appear here because there were some merge conflicts in 2 files. But those code changes should already be present in the upstream `annie` repository. (I don't fully understand why they turn up here as additions)

The neutron capture models were added in PR#10, and the different PMT glass reflectivities were added in PR#8.

Regarding the neutron capture code, I used the code adaptions that were also present in the nuPRISM WCSim repo, and just added the ANNRI model classes as additional options. I haven't really validated each individual call though, so that could be an interesting study. The neutron capture model seems to reasonably reproduce our calibration data, and the number of emitted gammas and their energies look as expected. But I haven't checked which cross-section is used - I would assume it's just the HP one, but it should probably be checked as you say. The ratio of captures on 155Gd/157Gd/hydrogen looked roughly correct, but I didn't do any further checks in that direction. The same is true for the material-specific thermal neutron modelling.

The R7081 reflectivities were introduced to investigate whether individual reflectivities would yield better results than individual Q.E. scaling factors (since different PMT types might have slightly different glass properties). However, this does not seem to be the case since the glass reflectivities and Q.E. scaling factors are pretty (anti-)correlated, so the effect can simply be absorbed in the Q.E. ratios. So currently the R7081 reflectivities are just set to the same value as the other PMTs. The separate reflectivities might be interesting in the future in case we need to do some more tuning, but we can also get rid of the factors if they bloat up the code too much.
If we decide to keep them, I can add a short comment line, sure.

**Comment by marc1uk** [comment]
> So most of these changes were in other PRs and ... should already be present in the upstream annie repository. The neutron capture models were added in PR#10, and the different PMT glass reflectivities were added in PR#8.

ok, probably my bad, i'm not yet familiar with how github's pull system works :sweat_smile: 

> The R7081 reflectivities ....

right, sorry I missed your response on #8  - i replied over there.

> Regarding the neutron capture code....

ok, perhaps the absence of comments is because this was copied over from another repo. If you're able to add any comments that explain what's happening as far as you understand it, or at least include a link to the relevant nuPRISM PR where this code was merged in, I think that would be a good idea. Similarly if you can publish any validation plots on PRs and put a comment with a link to them in the code, i think that's also probably a good practice.

**Comment by marc1uk** [comment]
i've just been trying to generate some muons (first time i've used WCSim in a while....).
I ran 100 muons fired into the MRD, which took 13 min 3 secs on my PC to process. I rolled back to a3b7525, re-built and re-ran the same WCSim.mac, and it took 8 min 41 secs to process 100 events with the same WCSim.mac file.
That's a 50% reduction in throughput with what's already been merged in. Perhaps the ANNRIGd is responsible for that, but I think it highlights that performance metrics are something to be aware of. 13 minutes for 100 muons is not fast - it means even fairly small jobs have to be done on the grid, which is kind of a pain.

**Comment by mnieslony** [comment]
Hi Marcus, thanks for pointing that out.
I did also notice that the runtime was slower than before, which I mainly attributed to increased reflections and probably the non-ideal handling of the PMT-specific Q.E. factors at the moment. The commit you are referring to seems to have happened before those changes were merged in, right? So I would suspect the ANNRI-Gd model has not too much to do with it, especially since you simulated muons. But I might be wrong about that.
In any case, I definitely agree that it would be preferable if we could make the simulation a little faster again. As you suggested in another PR, I suppose a good first step would be to save the Q.E. factors locally in the file where they are used and check how much that improves the speed compared to the current implementation.

**Comment by marc1uk** [comment]
sure, sounds good. Little tests like this that roll back to a past commit and compare performance could help narrow down where the drop is coming from, as an alternative to tweaking likely suspects such as QE factor implementation. a3b7525 is not so far back, you can find it just from git log and scrolling a little back.

**Pull request merged**
