### PR TITLE
ETEL & LUX holders

### PR DESCRIPTION
**Pull request by mnieslony**
ETEL & LUX holders were added to the ANNIE p2v7 geometry.
In addition, the size of the ANNIE holders was adjusted to avoid geometry overlaps. ETEL & LUX holders were also chosen to be slightly smaller than in reality to avoid overlaps also in their case.
The reflectivities of ETEL & LUX holders can be set independently from the reflectivity of the ANNIE holders, since they are made from a different material and have a different color (black instead of white). 

All_Holders_ANNIE_ETEL_LUX
LUX_Holders

### CODE REVIEW

**Review by marc1uk — CHANGES_REQUESTED** [review]
couple of comments in the conversation. Maybe that rebase would be good before merging though...

**Comment by marc1uk** [comment]
The changes look good, but i'm a bit puzzled why the PR involves 19 commits going all the way back to 2016?
Can you rebase your changes on the current anniesoft/annie branch, just to keep the history clean?

From your screenshot it also still looks like the subtraction solid putting the hole in the holder isn't going through, maybe that needs to be extended. With a subtraction solid i believe you don't need to line them up, you could just [make that subtracted cylinder as long as you like](https://github.com/ANNIEsoft/WCSim/pull/6/files#diff-c8ee549029ea47a6875f242b731722ac244a728b15740b59322f9adcdb5d3679R540), but just extending the length of the cylinder to 1.0 rather than 0.95 would be sufficient, for example.

[Why is it necessary for the duplication?](https://github.com/ANNIEsoft/WCSim/pull/6/files#diff-c8ee549029ea47a6875f242b731722ac244a728b15740b59322f9adcdb5d3679R544). I can see that having two different logical volumes could be useful for independently setting visualisation properties, but don't see much need for two identical solids. 

In terms of the [reflectivity arrays](https://github.com/ANNIEsoft/WCSim/pull/6/files#diff-d6346ffd4aaf49203bb9e76adb4664bf33595f8fafa94e36e6fda89a52f7e799R1112), with a material type of dielectric_metal we do need the arrays of reflectivity type, although i think we don't technically need the SigmaAlpha ([slide 13](https://indico.cern.ch/event/789510/contributions/3279418/attachments/1818134/2972494/AH_OpticalPhotons_slides.pdf)) - they effectively define how 'diffuse' the reflection is, which may well be different between the teflon wrapped steel structure (more diffuse) and the fairly shiny smooth plastic holders (more specular). So perhaps those arrays need to be different between the two optical surfaces.... although where you get the corresponding numbers from is the million dollar question.

**Comment by mnieslony** [comment]
Hi @marc1uk,
Thanks for looking through the PR. I tried to rebase to ANNIEsoft/annie, let me know if that worked fine - At least the number of commits has gone down from 19 to 7, so I suppose that's a good sign.

Regarding the cylinder holes in the holders, we could for sure make them longer as you suggest. I was wondering whether we can just leave the holders as they are right now without a hole, since in reality the rest of the PMT would block the way to the hole anyway. What do you think?

You're right, we could remove the solid `solidETELHolder` without any problems, it's not really necessary and just a duplication.

I unfortunately also don't know where we would get the reflectivity values, so for now I guess the best bet would just be to keep the current numbers and hope it's good enough?

**Comment by marc1uk** [comment]
> I tried to rebase to ANNIEsoft/annie, let me know if that worked fine - At least the number of commits has gone down from 19 to 7, so I suppose that's a good sign.

Easiest way to check would be to make another branch from your old (merged) version before the rebase, then compare the two branches. If the rebase worked, the `git diff rebased_ver merged_ver` should return nothing, because the resulting code is the same, just a cleaner history.
From what I can see, the commits before and after only differ by the additional variable `HolderrffLUX` in `include/WCSimRootOptions.hh` - somehow in your rebase that variable didn't get copied across. 
(Interestingly having done a 'review' and marked all the files as viewed, github did a lot of legwork and the review indicates that only `WCSimRootOptions.hh` changed since the review was done! Although it doesn't show you what changed since then, i still had to hack that out of the old commit. :upside_down_face:  .)

> I was wondering whether we can just leave the holders as they are right now without a hole, since in reality the rest of the PMT would block the way to the hole anyway. What do you think?

I think a good option for the ETEL/LUX holders would actually be to replace the use of subtractionsolid with a suitable additionsolid (or whatever its called) - a tube between the wings and the PMT bulb is actually a good representation of the real holder, and you've basically got the code already done for it (with that sub->add switch and slight change of dimensions).
For the ANNIE holders, whether hole or no hole is the better lazy option is less clear cut. In either case I think including a subtraction solid that doesn't work is just a bit misleading - have it and make it work, or remove it. 
My feeling is that including the hole would be slightly more representative, but that is just a guess. 

> I unfortunately also don't know where we would get the reflectivity values, so for now I guess the best bet would just be to keep the current numbers and hope it's good enough?

yeah as long as the reflectivity is roughly right it's probably good enough. :man_shrugging:

**Comment by mnieslony** [comment]
Ok, so the LUX & ETEL tubes now also have their housings included in the simulation & the ANNIE holders have holes that go all the way through.

The black sheet was also adjusted such that it extends below the housings of the LUX tubes at the bottom and above the ETEL holders at the top (here the ETEL housings go through holes in the black sheet and extend beyond the black sheet). 

I guess we don't necessarily need the ETEL housings since they are outside of the volume enclosed by the black sheet, but maybe it doesn't hurt to have them.
LUX_ETEL_Housings

**Comment by marc1uk** [comment]
Hi Michael, 
Sorry these PRs have been stagnating for ages now. :sweat:  Gonna try'n pull everything up to date over the next day or so.... hopefully. :grimacing: 
I realise there are several PRs on top of this one, so maybe some of these points become moot.
I think the best thing to do is to work through the PRs, make comments, and merge them. Once everything's in, if you can submit a PR with any requested changes that haven't been made moot by the final merge, rather than needing to change and rebase ancient commits.

That said, i can't see any issues with this (other than removing cruft lines like [this](https://github.com/ANNIEsoft/WCSim/pull/6/files#diff-c8ee549029ea47a6875f242b731722ac244a728b15740b59322f9adcdb5d3679R508) and [this](
https://github.com/ANNIEsoft/WCSim/pull/6/files#diff-c8ee549029ea47a6875f242b731722ac244a728b15740b59322f9adcdb5d3679R591)
git keeps the history if we need it, and i don't think we'd ever go back to a geometry with overlaps :sweat_smile: 
it just makes the code bloated and harder to read... not something we need more of.
if there are notes to be made on why the numbers changed, comment lines are welcome. :)

**Pull request merged**
