### PR TITLE
Tuning factors (relies on PR #6)

### PR DESCRIPTION
**Pull request by mnieslony**
Additional tuning factors are introduced in this PR, which are described in the following:

* `QERatio`: Scaling factor for counting p.e. at the PMT level for Hamamatsu/ANNIE PMTs
* `QERatioWB`: Scaling factor for counting p.e. at the PMT level for all other PMT types (Watchboy, Watchman, LUX, ETEL)
* `RgcffR7081`: Separate cathode reflectivity factor for R7081 PMTs, compared to other PMTs.

Default values for the tuning factors were determined by comparing through-going muon and Michel electron samples and can be found in `macros/tuning_parameters.mac`:
```
QEratio  1.40
QEratioWB 1.00
RgcffR7081 0.32
teflonrff 1.00
holderrff 0.90
holderrfflux 0.70
linerrff 0.87
```

The factors might change slightly in the future when doing some more fine-tuning with additional data samples.

### CODE REVIEW

**Comment by mnieslony** [comment]
Some supplementary plots showing the agreement between data and MC for the current tuning parameters. For the plots related to the through-going muon sample, the red histogram represents the MC and the blue histogram shows the data distribution.
ChargeDistributions_Ratio140_WBRatio100
MichelElectronSpectrum_Ratio140_WBRatio100

**Comment by marc1uk** [comment]
I'm curious what led to the introduction of a separate cathode reflectivity factor for R7081 PMTs, compared to other PMTs. How did this come about? If you're just changing the reflectivity, i'm not sure the specification of a different glass material is completely necessary.... but it probably doesn't hurt either. :man_shrugging: Just extra complexity if it isn't.

It would be nice to see the comparison plots with higher statistics, but this is a great start for first tuning. :+1: 

not sure what [this change](https://github.com/ANNIEsoft/WCSim/pull/8/files/cde18b29e44ac616b01391a070172958ca01f0f8..61f78059ab7fb4aecbb23ef5dee6cecf00c26550#diff-b63e366f4c624a87fbd619954618e5021b04e46165e756231c114addec2ee67aR44) is for....

[remove cruft...](https://github.com/ANNIEsoft/WCSim/pull/8/files/cde18b29e44ac616b01391a070172958ca01f0f8..61f78059ab7fb4aecbb23ef5dee6cecf00c26550#diff-551118888f53644ce3077b4c3c5616c3ff80bbf481e029efdff009b8726e829bR139). 
 there's so much code just commented out. -_-; it really doesn't help with readability....

For the code in WCSimStackingAction/WCSimWCSD::ProcessHits - there's nothing here that stands out in particular, but i'd be conscious that WCSim is a slooooow program, and this method gets called thousands of times per event, so anything that can be streamlined should be. e.g. rather than [getting tuning parameters](https://github.com/ANNIEsoft/WCSim/pull/8/files/cde18b29e44ac616b01391a070172958ca01f0f8..61f78059ab7fb4aecbb23ef5dee6cecf00c26550#diff-551118888f53644ce3077b4c3c5616c3ff80bbf481e029efdff009b8726e829bR109) and [QE ratios](https://github.com/ANNIEsoft/WCSim/pull/8/files/cde18b29e44ac616b01391a070172958ca01f0f8..61f78059ab7fb4aecbb23ef5dee6cecf00c26550#diff-551118888f53644ce3077b4c3c5616c3ff80bbf481e029efdff009b8726e829bR116) in every call, just get them once and store the result locally.

What's the relevance of 133 [here](https://github.com/ANNIEsoft/WCSim/pull/8/files/cde18b29e44ac616b01391a070172958ca01f0f8..61f78059ab7fb4aecbb23ef5dee6cecf00c26550#diff-551118888f53644ce3077b4c3c5616c3ff80bbf481e029efdff009b8726e829bR114)?

[remove cruft](https://github.com/ANNIEsoft/WCSim/pull/8/files/cde18b29e44ac616b01391a070172958ca01f0f8..61f78059ab7fb4aecbb23ef5dee6cecf00c26550#diff-551118888f53644ce3077b4c3c5616c3ff80bbf481e029efdff009b8726e829bR251)

It took me a good while to figure out if all the QE scalings are consistent - I think they are, but boy is it convoluted :grimacing: 
One thing that could be done to make it simpler is to remove the use of QEratio in the stacking action and max QE calculation of WCSimWCSD::ProcessHits. I think if it's removed from both, then it shouldn't make a difference. That would mean all the fudge factors are at least in one place (ProcessHits).
The introduction of the PMT-wise QE fudge factor could also make the WB-wide PMT type fudge factor redundant - i.e. just apply QEratioWB to all the WB PMTs in the input file, and remove it from WCSim.

**Comment by mnieslony** [comment]
Hey Marcus,

> I'm curious what led to the introduction of a separate cathode reflectivity factor for R7081 PMTs, compared to other PMTs. How did this come about? If you're just changing the reflectivity, i'm not sure the specification of a different glass material is completely necessary.... but it probably doesn't hurt either. 🤷‍♂️ Just extra complexity if it isn't.

This was just an idea to explore whether custom PMT-type reflectivity values might be better than PMT-type Q.E. scaling factors. In the end, both are pretty (anti)-correlated, so varying the reflectivity didn't seem to provide a better result than just scaling the Q.E. But it could still be used in the future in case we realize it might be useful.

> 
> It would be nice to see the comparison plots with higher statistics, but this is a great start for first tuning. 👍
> 
> not sure what [this change](https://github.com/ANNIEsoft/WCSim/pull/8/files/cde18b29e44ac616b01391a070172958ca01f0f8..61f78059ab7fb4aecbb23ef5dee6cecf00c26550#diff-b63e366f4c624a87fbd619954618e5021b04e46165e756231c114addec2ee67aR44) is for....
> 
> [remove cruft...](https://github.com/ANNIEsoft/WCSim/pull/8/files/cde18b29e44ac616b01391a070172958ca01f0f8..61f78059ab7fb4aecbb23ef5dee6cecf00c26550#diff-551118888f53644ce3077b4c3c5616c3ff80bbf481e029efdff009b8726e829bR139). there's so much code just commented out. -_-; it really doesn't help with readability....

You're probably right... The commented lines were mainly left there to provide a reference about what's used in the upstream version of WCSim.

> For the code in WCSimStackingAction/WCSimWCSD::ProcessHits - there's nothing here that stands out in particular, but i'd be conscious that WCSim is a slooooow program, and this method gets called thousands of times per event, so anything that can be streamlined should be. e.g. rather than [getting tuning parameters](https://github.com/ANNIEsoft/WCSim/pull/8/files/cde18b29e44ac616b01391a070172958ca01f0f8..61f78059ab7fb4aecbb23ef5dee6cecf00c26550#diff-551118888f53644ce3077b4c3c5616c3ff80bbf481e029efdff009b8726e829bR109) and [QE ratios](https://github.com/ANNIEsoft/WCSim/pull/8/files/cde18b29e44ac616b01391a070172958ca01f0f8..61f78059ab7fb4aecbb23ef5dee6cecf00c26550#diff-551118888f53644ce3077b4c3c5616c3ff80bbf481e029efdff009b8726e829bR116) in every call, just get them once and store the result locally.

That's a very good point, that should be investigated in the future to speed up things a little.

> What's the relevance of 133 [here](https://github.com/ANNIEsoft/WCSim/pull/8/files/cde18b29e44ac616b01391a070172958ca01f0f8..61f78059ab7fb4aecbb23ef5dee6cecf00c26550#diff-551118888f53644ce3077b4c3c5616c3ff80bbf481e029efdff009b8726e829bR114)?

133 was used as a cut value to only apply the Q.E. correction for PMTs and not for LAPPDs. Maybe there's a better way to do it, but it at least seemed to work like this.

> [remove cruft](https://github.com/ANNIEsoft/WCSim/pull/8/files/cde18b29e44ac616b01391a070172958ca01f0f8..61f78059ab7fb4aecbb23ef5dee6cecf00c26550#diff-551118888f53644ce3077b4c3c5616c3ff80bbf481e029efdff009b8726e829bR251)
> 
> It took me a good while to figure out if all the QE scalings are consistent - I think they are, but boy is it convoluted 😬 One thing that could be done to make it simpler is to remove the use of QEratio in the stacking action and max QE calculation of WCSimWCSD::ProcessHits. I think if it's removed from both, then it shouldn't make a difference. That would mean all the fudge factors are at least in one place (ProcessHits). The introduction of the PMT-wise QE fudge factor could also make the WB-wide PMT type fudge factor redundant - i.e. just apply QEratioWB to all the WB PMTs in the input file, and remove it from WCSim.

Yeah, storing the ratios locally is a good idea and should be done in the future. I think I would keep the `QEratioWB` parameter for now just in case someone wants to use PMT-type specific factors at some point (although currently they do not seem to provide a very good agreement compared to the other configurations)

**Comment by marc1uk** [comment]
> 133 was used as a cut value to only apply the Q.E. correction for PMTs and not for LAPPDs. Maybe there's a better way to do it, but it at least seemed to work like this.

how about using [the `isPMT` boolean?](https://github.com/ANNIEsoft/WCSim/pull/8/files/cde18b29e44ac616b01391a070172958ca01f0f8..61f78059ab7fb4aecbb23ef5dee6cecf00c26550#diff-551118888f53644ce3077b4c3c5616c3ff80bbf481e029efdff009b8726e829bR130) :upside_down_face:  

>  I think I would keep the QEratioWB parameter for now just in case someone wants to use PMT-type specific factors at some point (although currently they do not seem to provide a very good agreement compared to the other configurations)

Two things:
1. We can keep QEratioWB functionality, while still removing it from the stacking action. That helps group all the tuning factors into one place, making things easier to keep track of. At worst I think this would have a, probably negligible, effect on efficiency by increasing the number of tracked photons. The total QE that gets applied is ultimately a product of QE at the stacking action and the remaining QE applied at the detector. In the stacking action you apply `1/QE_stack`, and in the detector you apply `QE_actual / QE_stack`. Right now you choose either QE_normal or QE_WB in both stacking and sensitive detector, but you could just always use QE_normal in the stacking action, and then use `QE_actual*(QE_WB/QE_normal) / QE_stack` or `QE_actual/QE_stack` in the sensitive detector, and you have the same final result. 

2. more importantly, if you're applying PMT-specific QEs, you can just multiply all the QE numbers in your watchboy text file by QE_WB outside of WCSim. In my opinion this is by far the most general and uniform solution, and again much simplifies the WCSim code. I'd just remove QE_WB entirely, to be honest.....

**Comment by marc1uk** [comment]
> This was just an idea to explore whether custom PMT-type reflectivity values might be better than PMT-type Q.E. scaling factors. In the end, both are pretty (anti)-correlated, so varying the reflectivity didn't seem to provide a better result than just scaling the Q.E. But it could still be used in the future in case we realize it might be useful.

I appreciate the effort that went into developing this functionality, and it sucks to just discard that code and its associated work, but I think preserving this kind of thing "just in case" is another source of code bloat. It's preserved in git if you need it, or you can keep a local copy of a `git diff` patch file to record all the changes if you decide to reintroduce it in the future. But WCSim has a lot of tuning and fudge factors already that make tuning a complex, multi-dimensional and poorly documented process. I personally think that if the study was done and the conclusion was that it didn't help, I'd be inclined to remove it. If you honestly think you might come back to it, then I guess we can leave it in as a work in progress.

**Pull request merged**
